name: Run Tests

on:
  push:
    branches: [main, lab1, lab2, lab3, lab4, lab5] # Запуск при пуше в ветку
  pull_request:
    branches: [lab2, lab3, lab4, lab5] # Запуск при создании PR

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # Клонирование репозитория

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.16.0" # Node.js
          cache: "npm" # Кэширование зависимостей

      - name: Install dependencies
        run: npm ci # Чистая установка зависимостей

      - name: Run tests
        run: npx vitest src/test/main5.test.ts # Запуск тестов
